nextcloudappstore/urls.py
from allauth.account.views import signup
from allauth.socialaccount.views import signup as social_signup
from csp.decorators import csp_update
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.views.decorators.http import etag

from nextcloudappstore.core.caching import app_rating_etag
from nextcloudappstore.core.feeds import AppReleaseAtomFeed, AppReleaseRssFeed
from nextcloudappstore.core.views import (
    AppDetailView,
    AppRatingApi,
    AppRegisterView,
    AppReleasesView,
    AppUploadView,
    CategoryAppListView,
    app_description,
)
from nextcloudappstore.scaffolding.views import (
    AppScaffoldingView,
    IntegrationScaffoldingView,
)

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path("", CategoryAppListView.as_view(), {"id": None}, name="home"),
    path("featured", CategoryAppListView.as_view(), {"id": None, "is_featured_category": True}, name="featured"),
    path("signup/", csp_update(**settings.CSP_SIGNUP)(signup), name="account_signup"),
    path("social/signup/", csp_update(**settings.CSP_SIGNUP)(social_signup), name="socialaccount_signup"),
    path("", include("allauth.urls")),
    re_path(r"^categories/(?P<id>[\w]*)/?$", CategoryAppListView.as_view(), name="category-app-list"),
    re_path(r"^developer/apps/generate/?$", AppScaffoldingView.as_view(), name="app-scaffold"),
    re_path(r"^developer/integration/new/?$", IntegrationScaffoldingView.as_view(), name="integration-scaffold"),
    re_path(r"^developer/apps/releases/new/?$", AppUploadView.as_view(), name="app-upload"),
    re_path(r"^developer/apps/new/?$", AppRegisterView.as_view(), name="app-register"),
    re_path(r"^apps/(?P<id>[\w_]+)/?$", AppDetailView.as_view(), name="app-detail"),
    re_path(r"^apps/(?P<id>[\w_]+)/releases/?$", AppReleasesView.as_view(), name="app-releases"),
    re_path(r"^apps/(?P<id>[\w_]+)/description/?$", app_description, name="app-description"),
    re_path(r"^apps/(?P<id>[\w_]+)/ratings.json$", etag(app_rating_etag)(AppRatingApi.as_view()), name="app-ratings"),
    path("api/", include("nextcloudappstore.api.urls", namespace="api")),
    path("account/", include("nextcloudappstore.user.urls", namespace="user")),
    re_path(r"^admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("captcha/", include("captcha.urls")),
]

urlpatterns += i18n_patterns(
    re_path(r"feeds/releases.rss", AppReleaseRssFeed(), name="feeds-releases-rss"),
    re_path(r"feeds/releases.atom", AppReleaseAtomFeed(), name="feeds-releases-atom"),
)

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

nextcloudappstore/user/urls.py
from django.urls import path, re_path

from nextcloudappstore.scaffolding.views import IntegrationScaffoldingView
from nextcloudappstore.user.views import (
    AccountView,
    APITokenView,
    AppealCommentsView,
    ChangeLanguageView,
    DeleteAccountView,
    IntegrationsView,
    PasswordView,
    TransferAppsView,
)

app_name = "user"

urlpatterns = [
    path("", AccountView.as_view(), name="account"),
    re_path(r"^integrations/?$", IntegrationsView.as_view(), name="account-integrations"),
    re_path(r"^integrations/(?P<pk>[a-z0-9_]+)/?$", IntegrationScaffoldingView.as_view(), name="account-integration"),
    re_path(
        r"^integrations/(?P<pk>[a-z0-9_]+)/moderate/?$",
        IntegrationScaffoldingView.as_view(),
        name="account-integration-moderate",
    ),
    re_path(r"^transfer-apps/?$", TransferAppsView.as_view(), name="account-transfer-apps"),
    re_path(r"^transfer-apps/(?P<pk>[a-z0-9_]+)/?$", TransferAppsView.as_view(), name="account-transfer-app"),
    re_path(r"^password/?$", PasswordView.as_view(), name="account-password"),
    re_path(r"^token/?$", APITokenView.as_view(), name="account-api-token"),
    re_path(r"^delete/?$", DeleteAccountView.as_view(), name="account-deletion"),
    re_path(r"^change-language/?$", ChangeLanguageView.as_view(), name="account-change-language"),
    re_path(r"^appeal-comments/?$", AppealCommentsView.as_view(), name="appeal-comments"),
]

nextcloudappstore/user/models.py
from django.db import models  # noqa

# Create your models here.

nextcloudappstore/user/forms.py
from allauth.account.forms import EmailAwarePasswordResetTokenGenerator
from allauth.account.utils import (
    filter_users_by_email,
    user_pk_to_url_str,
    user_username,
)
from allauth.socialaccount.models import SocialAccount
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth import get_user_model
from django.forms import CharField, EmailField, PasswordInput
from django.utils.translation import gettext_lazy as _


class SignupFormRecaptcha(forms.Form):
    """integrate a recaptcha field."""

    captcha = CaptchaField()
    first_name = CharField(max_length=30, label=_("First name"))
    last_name = CharField(max_length=30, label=_("Last name"))

    def signup(self, request, user):
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()


class DeleteAccountForm(forms.Form):
    email = EmailField(required=True, label=_("Your email address"))
    passwd = CharField(
        required=False,
        widget=PasswordInput(),
        label=_("Your password"),
        help_text=_("*Required if the account is registered with a password"),
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.user and self.user.email == email:
            return email
        raise forms.ValidationError(_("The given email address does not match your email address"))

    def clean_passwd(self):
        passwd = self.cleaned_data.get("passwd")
        if self.user:
            social_user = SocialAccount.objects.filter(user_id=self.user, provider="github").first()
            if social_user is not None or self.user.check_password(passwd):
                return passwd
        raise forms.ValidationError(_("Invalid password"))


class AccountForm(forms.ModelForm):
    passwd = CharField(
        widget=PasswordInput(),
        label=_("Confirm password"),
        help_text=_(
            "Password is required to prevent "
            "unauthorized users from changing your "
            "email address and resetting your "
            "password. This field does not update your "
            "password!"
        ),
    )

    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "email")

    def clean_email(self):
        value = self.cleaned_data["email"]
        users = filter_users_by_email(value)
        if [u for u in users if u.pk != self.instance.pk]:
            msg = _("This email address is already associated with another account.")
            raise forms.ValidationError(msg)
        return value

    def clean_passwd(self):
        value = self.cleaned_data["passwd"]
        if self.instance.check_password(value):
            return value
        else:
            raise forms.ValidationError(_("Invalid password"))


class CustomResetPasswordForm(forms.Form):
    # remove this class once issue #1307 is resolved django-allauth
    email = forms.EmailField(
        label=_("Email"),
        required=True,
        widget=forms.TextInput(
            attrs={
                "type": "email",
                "size": "30",
                "placeholder": _("Email address"),
            }
        ),
    )

    def clean_email(self):
        email = self.cleaned_data["email"]
        from allauth.account.adapter import get_adapter

        email = get_adapter().clean_email(email)
        self.users = filter_users_by_email(email, is_active=True)

        return self.cleaned_data["email"]

    def save(self, request, **kwargs):
        from django.contrib.sites.shortcuts import get_current_site

        current_site = get_current_site(request)
        email = self.cleaned_data["email"]
        token_generator = EmailAwarePasswordResetTokenGenerator()

        for user in self.users:
            temp_key = token_generator.make_token(user)

            # save it to the password reset model
            # password_reset = PasswordReset(user=user, temp_key=temp_key)
            # password_reset.save()

            # send the password reset email
            from django.urls import reverse

            path = reverse(
                "account_reset_password_from_key", kwargs=dict(uidb36=user_pk_to_url_str(user), key=temp_key)
            )
            from allauth.utils import build_absolute_uri

            url = build_absolute_uri(request, path)

            context = {"current_site": current_site, "user": user, "password_reset_url": url, "request": request}

            from allauth.account import app_settings

            if app_settings.AUTHENTICATION_METHOD != app_settings.AuthenticationMethod.EMAIL:
                context["username"] = user_username(user)
            from allauth.account.adapter import get_adapter

            get_adapter(request).send_mail("account/email/password_reset_key", email, context)
        return self.cleaned_data["email"]

nextcloudappstore/user/views.py
from allauth.account.models import EmailAddress
from allauth.account.views import PasswordChangeView
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, UpdateView

from nextcloudappstore.core.models import App, AppRating
from nextcloudappstore.user.forms import AccountForm, DeleteAccountForm


class IntegrationsView(LoginRequiredMixin, TemplateView):
    template_name = "user/integrations.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["apps"] = App.objects.filter(owner=self.request.user).filter(Q(is_integration=True) & Q(approved=True))
        if self.request.user.is_superuser:
            context["pending"] = App.objects.filter(is_integration=True).filter(approved=False)
        context["acc_page"] = "account-integrations"
        return context


class TransferAppsView(LoginRequiredMixin, TemplateView):
    template_name = "user/transfer-apps.html"

    def post(self, request, pk):
        app = get_object_or_404(App, pk=pk, owner=self.request.user)
        app.ownership_transfer_enabled = not app.ownership_transfer_enabled
        app.save()
        return redirect(reverse("user:account-transfer-apps"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["apps"] = App.objects.filter(owner=self.request.user)
        context["acc_page"] = "account-transfer-apps"
        return context


class ChangeLanguageView(LoginRequiredMixin, TemplateView):
    template_name = "user/set-language.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "account-change-language"
        return context


class DeleteAccountView(LoginRequiredMixin, TemplateView):
    template_name = "user/delete-account.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = DeleteAccountForm()
        context["acc_page"] = "delete-account"
        return context

    def post(self, request, *args, **kwargs):
        form = DeleteAccountForm(request.POST, user=request.user)
        if not form.is_valid():
            return render(request, self.template_name, {"form": form})

        request.user.delete()
        return redirect(reverse_lazy("home"))


class AccountView(LoginRequiredMixin, UpdateView):
    """Display and allow changing of the user's name."""

    template_name = "user/account.html"
    template_name_suffix = ""
    form_class = AccountForm
    success_url = reverse_lazy("user:account")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "account"
        return context

    def form_invalid(self, form):
        failed_attempts = self.request.session.get("account_update_failed_count", 0)
        if failed_attempts >= 15:
            logout(self.request)
            return HttpResponseRedirect("/")
        self.request.session["account_update_failed_count"] = failed_attempts + 1
        return super().form_invalid(form)

    def form_valid(self, form):
        email = EmailAddress.objects.get_primary(user=self.request.user)
        if email.email != form.cleaned_data["email"]:
            email.email = form.cleaned_data["email"]
            email.save(update_fields=["email"])
        messages.success(self.request, "Account details saved.")
        self.request.session["account_update_failed_count"] = 0
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user


class PasswordView(LoginRequiredMixin, PasswordChangeView):
    """Allow the user to change their password."""

    template_name = "user/password.html"
    success_url = reverse_lazy("user:account-password")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "password"
        return context


class APITokenView(LoginRequiredMixin, TemplateView):
    """Display the user's API token, and allow it to be regenerated."""

    template_name = "user/api-token.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "api-token"
        return context


class AppealCommentsView(LoginRequiredMixin, TemplateView):
    template_name = "user/appeal-comments.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_superuser:
            # context["pending"] = AppRating.objects.filter(appeal=True)
            pending_ratings = AppRating.objects.filter(appeal=True)
            pending_with_lang = [
                {
                    "rating": rating,
                    "lang": rating.translations.first().language_code if rating.translations.exists() else None,
                }
                for rating in pending_ratings
            ]
            context["pending"] = pending_with_lang
        context["acc_page"] = "appeal-comments"
        return context

nextcloudappstore/user/templates/user/account.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{% block head-title %}{% trans 'Account' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Account" %}</h1>
    <section>
        <form action="{% url 'user:account' %}" method="post">
            {% include 'form-fields.html' %}
            <p>
                <button class="btn btn-primary btn-block" type="submit">
                    <span class="icon material-symbols-outlined">done</span>
                    {% trans 'Save' %}
                </button>
            </p>
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/api-token.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{% block head %}
    <script defer src="{% static 'public/user/token.js' %}"></script>
{% endblock %}

{% block head-title %}{% trans 'API Token' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "API Token" %}</h1>
    <section id="tokenSection">
        <p>
            {% blocktrans %}
                The API token can be used for authentication when calling the Nextcloud app store
                <a href="https://nextcloudappstore.readthedocs.io/en/latest/restapi.html">REST API</a>.
                Make sure to keep it secret. A new token can be generated below, rendering the old token invalid.
            {% endblocktrans %}
        </p>

        <p>{% trans 'Your API token is:' %}</p>

        <!-- DO NOT print the HTML token here because of BREACH attack but fetch it with JS -->
        <p><code id="token"></code></p>
        <form action="{% url 'api:v1:user-token-new' %}" method="post" id="api-token-regen-form">
            <span data-l10n-id="msg-form-success" hidden>{% trans 'New API token generated.' %}</span>
            <div><div class="hidden alert alert-success global-success-msg" hidden></div></div>
            <div><div class="alert alert-danger global-error-msg" hidden></div></div>

            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-block" value="{% trans 'Regenerate API token' %}" disabled="disabled">
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/appeal-comments.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{% block head-title %}{% trans 'Appeal commentaries' %} - {% endblock %}

{% block account-content %}
    {% if user.is_superuser %}
        <h1>{% trans "Comments Pending Appeal" %}</h1>
        <section>
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'App' %}</th>
                    <th>{% trans 'Comment author' %}</th>
                    <th>{% trans 'Link' %}</th>
                </tr>
                {% for item in pending %}
                    <tr>
                        <td>{{ item.rating.app }}</td>
                        <td>{{ item.rating.user }}</td>
                        <td>
                            <form action="{% url 'app-detail' id=item.rating.app.id %}" method="get">
                                <input type="hidden" name="comment_id" value="{{ item.rating.id }}">
                                <input type="hidden" name="bad_comment_lang" value="{{ item.lang }}">
                                <button class="btn btn-primary btn-block" type="submit">{% trans 'Go to' %}</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </section>
    {% endif %}

{% endblock %}

nextcloudappstore/user/templates/user/base.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block head-title %}{% trans "Account" %} - {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-4 col-md-3">
        <ul id="sidebar" class="nav nav-pills nav-stacked">
            <li class="{% if acc_page == 'account' %}active{% endif %}">
                <a href="{% url 'user:account' %}">
                    <span class="icon material-symbols-outlined">person</span>
                    {% trans 'Account' %}
                </a>
            </li>
            <li class="{% if acc_page == 'account-integrations' %}active{% endif %}">
                <a href="{% url 'user:account-integrations' %}">
                    <span class="icon material-symbols-outlined">integration_instructions</span>
                    {% trans 'Integrations' %}
                </a>
            </li>
            <li class="{% if acc_page == 'account-transfer-apps' %}active{% endif %}">
                <a href="{% url 'user:account-transfer-apps' %}">
                    <span class="icon material-symbols-outlined">move_down</span>
                    {% trans 'Transfer app ownership' %}
                </a>
            </li>
            <li class="{% if acc_page == 'account-change-language' %}active{% endif %}">
                <a href="{% url 'user:account-change-language' %}">
                    <span class="icon material-symbols-outlined">translate</span>
                    {% trans 'Change language' %}
                </a>
            </li>
            {% if request.user.has_usable_password %}
                <li class="{% if acc_page == 'password' %}active{% endif %}">
                    <a href="{% url 'user:account-password' %}">
                        <span class="icon material-symbols-outlined">password</span>
                        {% trans 'Password' %}
                    </a>
                </li>
            {% endif %}
            <li class="{% if acc_page == 'api-token' %}active{% endif %}">
                <a href="{% url 'user:account-api-token' %}">
                    <span class="icon material-symbols-outlined">key</span>
                    {% trans 'API token' %}
                </a>
            </li>
            <li class="{% if acc_page == 'delete-account' %}active{% endif %}">
                <a href="{% url 'user:account-deletion' %}">
                    <span class="icon material-symbols-outlined">security</span>
                    {% trans 'Delete account' %}
                </a>
            </li>
            {% if user.is_superuser %}
                <li class="{% if acc_page == 'appeal-comments' %}active{% endif %}">
                    <a href="{% url 'user:appeal-comments' %}">
                        <span class="icon material-symbols-outlined">flag</span>
                        {% trans 'Appeal comments' %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="col-sm-8 col-md-9 account-content">
        {% block account-content %}{% endblock %}
    </div>
</div>
{% endblock %}

nextcloudappstore/user/templates/user/delete-account.html
{% extends "user/base.html" %}
{% load i18n %}
{% load account socialaccount css_class %}

{% block head-title %}{% trans "Delete account" %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Delete account" %}</h1>
    <section>
        <p class="alert alert-danger">{% trans 'Deleting your account will delete all your apps and releases as well. To delete your account, insert your email address into the input field and click the "Delete account" button.' %}</p>
        <form method="POST" action="{% url 'user:account-deletion' %}">
            {% include 'form-fields.html' %}
{#            <p><input type="submit" class="btn btn-danger" value="{% trans 'Delete account' %}"></p>#}
            <p>
                <button type="submit" class="btn btn-danger">
                    <span class="icon material-symbols-outlined">person_remove</span>
                    {% trans 'Delete account' %}
                </button>
            </p>
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/integrations.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{% block head-title %}{% trans 'Integrations' %} - {% endblock %}

{% block account-content %}
    {% if pending and user.is_superuser %}
        <h1>{% trans "Pending approval" %}</h1>
        <section>
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'Integration name' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                {% for app in pending %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td>
                            <form action="{% url 'user:account-integration-moderate' pk=app.id %}" method="get">
                                {% csrf_token %}
                                <button class="btn btn-primary btn-block" type="submit">{% trans 'View' %}</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </section>
    {% endif %}

    <h1>{% trans "Your integrations" %}</h1>
    <section>
        {% if apps %}
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'Integration name' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                {% for app in apps %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td>
                            <form action="{% url 'user:account-integration' pk=app.id %}" method="get">
                                {% csrf_token %}
                                <button class="btn btn-primary btn-block" type="submit">{% trans 'Edit' %}</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="alert alert-info">{% trans 'You have not submitted any integration yet or they are pending approval!' %}</p>
        {% endif %}
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/password.html
{% extends "user/base.html" %}
{% load i18n %}
{% load account socialaccount %}

{% block head-title %}{% trans "Password" %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Change Password" %}</h1>
    <section>
        <p class="text-danger">{% trans 'Changing your password will also regenerate your API token!' %}</p>
        {% if request.user.has_usable_password %}
            <form method="POST" action="{% url 'user:account-password' %}" class="password_change">
                {% include 'form-fields.html' %}
                <p>
                    <button class="btn btn-primary" type="submit">
                        <span class="icon material-symbols-outlined">done</span>
                        {% trans "Change Password" %}
                    </button>
                </p>
            </form>
        {% else %}
            <p>{% trans 'You seem to be using an account registered with a third-party provider. Your password can therefore <strong>not</strong> be changed from this page.' %}</p>
        {% endif %}
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/set-language.html
{% extends "user/base.html" %}
{% load i18n %}

{% block head-title %}{% trans "Change language" %} - {% endblock %}

{% block account-content %}
    <h1>{% trans 'Change language' %}</h1>
    <section>
        <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <div class="form-group">
                <label title="{% trans 'required field' %}" class="control-label" for="language">{% trans 'Language' %}<span class="required-field material-symbols-outlined">asterisk</span></label>

                <select name="language" id="language" class="form-control">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
            </div>
            <p>
                <button type="submit" class="btn btn-primary btn-block">
                    <span class="icon material-symbols-outlined">translate</span>
                    {% trans 'Change language' %}
                </button>
{#                <input type="submit" class="btn btn-primary btn-block" value="{% trans 'Change language' %}">#}
            </p>
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/transfer-apps.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{% block head-title %}{% trans 'Transfer Apps' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Transfer Apps" %}</h1>
    <section>
        <p>{% trans 'To transfer an app to a new owner you must first unlock the app. A user can then take control of the app by registering it again on the app register page in the app developer menu.' %}</p>

        {% if apps %}
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'App name' %}</th>
                    <th>{% trans 'Ownership transfer status' %}</th>
                    <th>{% trans 'Change ownership transfer status' %}</th>
                </tr>
                {% for app in apps %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td class="{% if app.ownership_transfer_enabled %}bg-success{% else %}bg-danger{% endif %}">
                            {% if app.ownership_transfer_enabled %}
                                {% trans 'Unlocked for transfer' %}
                            {% else %}
                                {% trans 'Locked, no transfer possible' %}
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'user:account-transfer-app' pk=app.id %}" method="post">
                                {% csrf_token %}
                                {% if app.ownership_transfer_enabled %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Lock ownership transfer' %}</button>
                                {% else %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Unlock ownership transfer' %}</button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="alert alert-info">{% trans 'You have not uploaded any apps yet!' %}</p>
        {% endif %}
    </section>
{% endblock %}